The following additional libraries are needed to run this
notebook. Note that running on Colab is experimental, please report a Github
issue if you have any problem.

In [1]:
!pip install git+https://github.com/d2l-ai/d2l-zh@release --no-deps --force-reinstall
!pip install numpy>=1.20

  Cloning https://github.com/d2l-ai/d2l-zh (to revision release) to /tmp/pip-req-build-ncnkfje5
  Running command git clone --filter=blob:none --quiet https://github.com/d2l-ai/d2l-zh /tmp/pip-req-build-ncnkfje5
  Running command git checkout -b release --track origin/release
  Switched to a new branch 'release'
  Branch 'release' set up to track remote branch 'release' from 'origin'.
  Resolved https://github.com/d2l-ai/d2l-zh to commit 843d3d41dca48d8df65f4b324dd171d8bfe9c067
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
  Created wheel for d2l: filename=d2l-2.0.0-py3-none-any.whl size=110800 sha256=a3709c5ce5a0214127793c68df508ad2854e9159ce0e89831dd90117a29ca457
  Stored in directory: /tmp/pip-ephem-wheel-cache-az4vadbl/wheels/53/15/45/14b38ed62d9bc53ab3de439d4c2a79f70a00112eeeadcf6c34
Successfully built d2l


# 图像卷积
:label:`sec_conv_layer`

上节我们解析了卷积层的原理，现在我们看看它的实际应用。由于卷积神经网络的设计是用于探索图像数据，本节我们将以图像为例。

## 互相关运算

严格来说，卷积层是个错误的叫法，因为它所表达的运算其实是*互相关运算*（cross-correlation），而不是卷积运算。
根据 :numref:`sec_why-conv`中的描述，在卷积层中，输入张量和核张量通过(**互相关运算**)产生输出张量。

首先，我们暂时忽略通道（第三维）这一情况，看看如何处理二维图像数据和隐藏表示。在 :numref:`fig_correlation`中，输入是高度为$3$、宽度为$3$的二维张量（即形状为$3 \times 3$）。卷积核的高度和宽度都是$2$，而卷积核窗口（或卷积窗口）的形状由内核的高度和宽度决定（即$2 \times 2$）。

![二维互相关运算。阴影部分是第一个输出元素，以及用于计算输出的输入张量元素和核张量元素：$0\times0+1\times1+3\times2+4\times3=19$.](http://d2l.ai/_images/correlation.svg)
:label:`fig_correlation`

在二维互相关运算中，卷积窗口从输入张量的左上角开始，从左到右、从上到下滑动。
当卷积窗口滑动到新一个位置时，包含在该窗口中的部分张量与卷积核张量进行按元素相乘，得到的张量再求和得到一个单一的标量值，由此我们得出了这一位置的输出张量值。
在如上例子中，输出张量的四个元素由二维互相关运算得到，这个输出高度为$2$、宽度为$2$，如下所示：

$$
0\times0+1\times1+3\times2+4\times3=19,\\
1\times0+2\times1+4\times2+5\times3=25,\\
3\times0+4\times1+6\times2+7\times3=37,\\
4\times0+5\times1+7\times2+8\times3=43.
$$

注意，输出大小略小于输入大小。这是因为卷积核的宽度和高度大于1，
而卷积核只与图像中每个大小完全适合的位置进行互相关运算。
所以，输出大小等于输入大小$n_h \times n_w$减去卷积核大小$k_h \times k_w$，即：

$$(n_h-k_h+1) \times (n_w-k_w+1).$$

这是因为我们需要足够的空间在图像上“移动”卷积核。稍后，我们将看到如何通过在图像边界周围填充零来保证有足够的空间移动卷积核，从而保持输出大小不变。
接下来，我们在`corr2d`函数中实现如上过程，该函数接受输入张量`X`和卷积核张量`K`，并返回输出张量`Y`。


In [2]:
import torch
from torch import nn
from d2l import torch as d2l

In [3]:
def corr2d(X, K):  #@save
    """计算二维互相关运算"""
    h, w = K.shape
    Y = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = (X[i:i + h, j:j + w] * K).sum() #还是逐个像素之间的相乘
    return Y

通过 :numref:`fig_correlation`的输入张量`X`和卷积核张量`K`，我们来[**验证上述二维互相关运算的输出**]。


In [4]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
K = torch.tensor([[0.0, 1.0], [2.0, 3.0]])
corr2d(X, K)

tensor([[19., 25.],
        [37., 43.]])

## 卷积层

卷积层对输入和卷积核权重进行互相关运算，并在添加标量偏置之后产生输出。
所以，卷积层中的两个被训练的参数是卷积核权重和标量偏置。
就像我们之前随机初始化全连接层一样，在训练基于卷积层的模型时，我们也随机初始化卷积核权重。

基于上面定义的`corr2d`函数[**实现二维卷积层**]。在`__init__`构造函数中，将`weight`和`bias`声明为两个模型参数。前向传播函数调用`corr2d`函数并添加偏置。


In [5]:
class Conv2D(nn.Module):
    def __init__(self, kernel_size):
        super().__init__()
        self.weight = nn.Parameter(torch.rand(kernel_size))
        self.bias = nn.Parameter(torch.zeros(1))

    def forward(self, x):
        return corr2d(x, self.weight) + self.bias

高度和宽度分别为$h$和$w$的卷积核可以被称为$h \times w$卷积或$h \times w$卷积核。
我们也将带有$h \times w$卷积核的卷积层称为$h \times w$卷积层。

## 图像中目标的边缘检测

如下是[**卷积层的一个简单应用：**]通过找到像素变化的位置，来(**检测图像中不同颜色的边缘**)。
首先，我们构造一个$6\times 8$像素的黑白图像。中间四列为黑色（$0$），其余像素为白色（$1$）。


In [6]:
X = torch.ones((6, 8))
X[:, 2:6] = 0
X

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]])

接下来，我们构造一个高度为$1$、宽度为$2$的卷积核`K`。当进行互相关运算时，如果水平相邻的两元素相同，则输出为零，否则输出为非零。


In [7]:
K = torch.tensor([[1.0, -1.0]])

现在，我们对参数`X`（输入）和`K`（卷积核）执行互相关运算。
如下所示，[**输出`Y`中的1代表从白色到黑色的边缘，-1代表从黑色到白色的边缘**]，其他情况的输出为$0$。


In [8]:
Y = corr2d(X, K)
Y

tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.]])

现在我们将输入的二维图像转置，再进行如上的互相关运算。
其输出如下，之前检测到的垂直边缘消失了。
不出所料，这个[**卷积核`K`只可以检测垂直边缘**]，无法检测水平边缘。


In [ ]:
corr2d(X.t(), K)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

## 学习卷积核

如果我们只需寻找黑白边缘，那么以上`[1, -1]`的边缘检测器足以。然而，当有了更复杂数值的卷积核，或者连续的卷积层时，我们不可能手动设计滤波器。那么我们是否可以[**学习由`X`生成`Y`的卷积核**]呢？

现在让我们看看是否可以通过仅查看“输入-输出”对来学习由`X`生成`Y`的卷积核。
我们先构造一个卷积层，并将其卷积核初始化为随机张量。接下来，在每次迭代中，我们比较`Y`与卷积层输出的平方误差，然后计算梯度来更新卷积核。为了简单起见，我们在此使用内置的二维卷积层，并忽略偏置。


In [9]:
# 构造一个二维卷积层，它具有1个输出通道和形状为（1，2）的卷积核
conv2d = nn.Conv2d(1,1, kernel_size=(1, 2), bias=False)

# 这个二维卷积层使用四维输入和输出格式（批量大小、通道、高度、宽度），
# 其中批量大小和通道数都为1
X = X.reshape((1, 1, 6, 8))
Y = Y.reshape((1, 1, 6, 7))
lr = 3e-2  # 学习率

for i in range(10):
    Y_hat = conv2d(X)
    l = (Y_hat - Y) ** 2
    conv2d.zero_grad()
    l.sum().backward()
    # 迭代卷积核
    conv2d.weight.data[:] -= lr * conv2d.weight.grad
    if (i + 1) % 2 == 0:
        print(f'epoch {i+1}, loss {l.sum():.3f}')

epoch 2, loss 11.459
epoch 4, loss 2.837
epoch 6, loss 0.850
epoch 8, loss 0.296
epoch 10, loss 0.113


在$10$次迭代之后，误差已经降到足够低。现在我们来看看我们[**所学的卷积核的权重张量**]。


In [10]:
conv2d.weight.data.reshape((1, 2))

tensor([[ 0.9519, -1.0193]])

细心的读者一定会发现，我们学习到的卷积核权重非常接近我们之前定义的卷积核`K`。

## 互相关和卷积

回想一下我们在 :numref:`sec_why-conv`中观察到的互相关和卷积运算之间的对应关系。
为了得到正式的*卷积*运算输出，我们需要执行 :eqref:`eq_2d-conv-discrete`中定义的严格卷积运算，而不是互相关运算。
幸运的是，它们差别不大，我们只需水平和垂直翻转二维卷积核张量，然后对输入张量执行*互相关*运算。

值得注意的是，由于卷积核是从数据中学习到的，因此无论这些层执行严格的卷积运算还是互相关运算，卷积层的输出都不会受到影响。
为了说明这一点，假设卷积层执行*互相关*运算并学习 :numref:`fig_correlation`中的卷积核，该卷积核在这里由矩阵$\mathbf{K}$表示。
假设其他条件不变，当这个层执行严格的*卷积*时，学习的卷积核$\mathbf{K}'$在水平和垂直翻转之后将与$\mathbf{K}$相同。
也就是说，当卷积层对 :numref:`fig_correlation`中的输入和$\mathbf{K}'$执行严格*卷积*运算时，将得到与互相关运算 :numref:`fig_correlation`中相同的输出。

为了与深度学习文献中的标准术语保持一致，我们将继续把“互相关运算”称为卷积运算，尽管严格地说，它们略有不同。
此外，对于卷积核张量上的权重，我们称其为*元素*。

## 特征映射和感受野

如在 :numref:`subsec_why-conv-channels`中所述， :numref:`fig_correlation`中输出的卷积层有时被称为*特征映射*（feature map），因为它可以被视为一个输入映射到下一层的空间维度的转换器。
在卷积神经网络中，对于某一层的任意元素$x$，其*感受野*（receptive field）是指在前向传播期间可能影响$x$计算的所有元素（来自所有先前层）。

请注意，感受野可能大于输入的实际大小。让我们用 :numref:`fig_correlation`为例来解释感受野：
给定$2 \times 2$卷积核，阴影输出元素值$19$的感受野是输入阴影部分的四个元素。
假设之前输出为$\mathbf{Y}$，其大小为$2 \times 2$，现在我们在其后附加一个卷积层，该卷积层以$\mathbf{Y}$为输入，输出单个元素$z$。
在这种情况下，$\mathbf{Y}$上的$z$的感受野包括$\mathbf{Y}$的所有四个元素，而输入的感受野包括最初所有九个输入元素。
因此，当一个特征图中的任意元素需要检测更广区域的输入特征时，我们可以构建一个更深的网络。

## 小结

* 二维卷积层的核心计算是二维互相关运算。最简单的形式是，对二维输入数据和卷积核执行互相关操作，然后添加一个偏置。
* 我们可以设计一个卷积核来检测图像的边缘。
* 我们可以从数据中学习卷积核的参数。
* 学习卷积核时，无论用严格卷积运算或互相关运算，卷积层的输出不会受太大影响。
* 当需要检测输入特征中更广区域时，我们可以构建一个更深的卷积网络。

## 练习

1. 构建一个具有对角线边缘的图像`X`。
    1. 如果将本节中举例的卷积核`K`应用于`X`，会发生什么情况？
    1. 如果转置`X`会发生什么？
    1. 如果转置`K`会发生什么？
1. 在我们创建的`Conv2D`自动求导时，有什么错误消息？
1. 如何通过改变输入张量和卷积核张量，将互相关运算表示为矩阵乘法？
1. 手工设计一些卷积核。
    1. 二阶导数的核的形式是什么？
    1. 积分的核的形式是什么？
    1. 得到$d$次导数的最小核的大小是多少？


In [14]:
import torch
import torch.nn as nn

X = torch.tensor([
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 0, 0, 0],
    [0, 0, 0, 1, 1, 1],
    [0, 0, 0, 1, 1, 1],
    [0, 0, 0, 1, 1, 1]
], dtype=torch.float32).view(1, 1, 6, 6)  # 形状 [batch=1, channel=1, height=6, width=6]
# 定义卷积层（输入通道=1，输出通道=1，核大小=3x3，无偏置）
conv = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, bias=False) #（1，1，3，3）

# 手动设置卷积核（垂直边缘检测）
K = torch.tensor([
    [[[1, 0, -1],
      [1, 0, -1],
      [1, 0, -1]]]#这个形状就是1 1 3 3
], dtype=torch.float32)
conv.weight.data = K  # 权重形状 [out_channels=1, in_channels=1, 3, 3]
output = conv(X)
print("原始输出:\n", output.squeeze())
X_transposed = X.transpose(2, 3)  # 交换宽度和高度维度 原来四维矩阵是这样交换的啊。
output_transposed_X = conv(X_transposed)
print("转置X后的输出:\n", output_transposed_X.squeeze())

transposed_kernel = conv.weight.data.transpose(2, 3)
output_both_transposed = conv(X_transposed)
print("同时转置X和K后的输出:\n", output_both_transposed.squeeze())

A = torch.rand(1, 3, 1, 2)
print(A.shape)  # 输出: torch.Size([1, 3, 1, 2])

B = A.squeeze()  # 移除所有长度为1的维度
print(B.shape)  # 输出: torch.Size([3, 2])


原始输出:
 tensor([[ 0.,  3.,  3.,  0.],
        [ 0.,  1.,  1.,  0.],
        [ 0., -1., -1.,  0.],
        [ 0., -3., -3.,  0.]], grad_fn=<SqueezeBackward0>)
转置X后的输出:
 tensor([[ 0.,  3.,  3.,  0.],
        [ 0.,  1.,  1.,  0.],
        [ 0., -1., -1.,  0.],
        [ 0., -3., -3.,  0.]], grad_fn=<SqueezeBackward0>)
同时转置X和K后的输出:
 tensor([[ 0.,  3.,  3.,  0.],
        [ 0.,  1.,  1.,  0.],
        [ 0., -1., -1.,  0.],
        [ 0., -3., -3.,  0.]], grad_fn=<SqueezeBackward0>)
torch.Size([1, 3, 1, 2])
torch.Size([3, 2])


In [ ]:
#第二个问题：
conv_layer = Conv2D(kernel_size=(3, 3))
x = torch.rand(1, 5, 5)  # 输入 [batch=1, H, W]
output = conv_layer(x)    # 输出是矩阵（非标量）

# 尝试自动求导
output.sum().backward()   # 必须手动转为标量才能求导

In [15]:
#第三个问题：
import torch
import torch.nn.functional as F

def conv2d_via_matmul(X, K):
    """
    通过矩阵乘法实现卷积（互相关）运算。
    参数：
        X: 输入张量，形状 (batch_size, in_channels, height, width)
        K: 卷积核，形状 (out_channels, in_channels, kernel_h, kernel_w)
    返回：
        输出张量，形状 (batch_size, out_channels, out_h, out_w)
    """
    batch_size, in_channels, height, width = X.shape
    out_channels, _, kernel_h, kernel_w = K.shape

    # 计算输出尺寸
    out_h = height - kernel_h + 1
    out_w = width - kernel_w + 1

    # 1. 展开输入为 im2col 矩阵 (kernel_h * kernel_w * in_channels, batch_size * out_h * out_w)
    '''
    F.unfold 的输入是一个 4D 张量（形状为 [batch_size, in_channels, height, width]），
    输出是一个 3D 张量（形状为 [batch_size, kernel_h * kernel_w * in_channels, out_h * out_w]）。
    它的核心功能是：将输入张量中每个卷积核覆盖的小区域展平为一列，所有列堆叠成一个矩阵。
    '''
    X_col = F.unfold(X, kernel_size=(kernel_h, kernel_w))  # 形状: (batch_size, kernel_h * kernel_w * in_channels, out_h * out_w)
    #F.unfold输入的是一个4D向量，输出的是一个3D向量
    X_col = X_col.reshape(batch_size, -1, out_h * out_w).permute(1, 0, 2).reshape(-1, batch_size * out_h * out_w)
    #（kernel_h * kernel_w * in_channels, batch_size， out_h * out_w )。（ kernel_h * kernel_w * in_channels， batch_size *out_h * out_w）

    # 2. 展开卷积核为矩阵 (out_channels, kernel_h * kernel_w * in_channels) 对，确实是把滑动改成了矩阵运算。
    K_row = K.reshape(out_channels, -1)

    # 3. 矩阵乘法
    Y_col = K_row @ X_col  # 形状: (out_channels, batch_size * out_h * out_w) #这里的每一个模版 也确实乘以了 kernel_h * kernel_w * in_channels
    #和在影像上滑动是一样的。

    # 4. 重塑为输出张量
    Y = Y_col.reshape(out_channels, batch_size, out_h, out_w).permute(1, 0, 2, 3)

    return Y

# 测试示例
if __name__ == "__main__":
    # 定义输入和卷积核
    X = torch.tensor([[
        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]
    ]], dtype=torch.float32)  # 形状: (1, 1, 3, 3)

    K = torch.tensor([[
        [[1, 0],
         [0, -1]]
    ]], dtype=torch.float32)  # 形状: (1, 1, 2, 2)

    # 使用矩阵乘法实现卷积
    Y_matmul = conv2d_via_matmul(X, K)
    print("矩阵乘法输出:\n", Y_matmul)

    # 使用 PyTorch 原生卷积验证
    Y_conv = F.conv2d(X, K, stride=1, padding=0)
    print("PyTorch 卷积输出:\n", Y_conv)

    # 检查结果是否一致
    print("结果是否一致:", torch.allclose(Y_matmul, Y_conv, atol=1e-6))

矩阵乘法输出:
 tensor([[[[-4., -4.],
          [-4., -4.]]]])
PyTorch 卷积输出:
 tensor([[[[-4., -4.],
          [-4., -4.]]]])
结果是否一致: True


In [16]:
import torch
import torch.nn.functional as F

# 输入：1张图，1通道，4x4
X = torch.tensor([[
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10,11,12],
     [13,14,15,16]]
]], dtype=torch.float32)

# 展开为 im2col 矩阵
unfolded = F.unfold(X, kernel_size=2) #3*3
print(unfolded.shape)  # 输出: torch.Size([1, 4, 9]) 这里面的1:batch size为 就是一张照片 4:就是核为2*2 每次滑动就展成一列。一共9个小方块 滑动了9次。

# 查看第一个局部区域（左上角 2x2）
print(unfolded[0, :, 0])  # 输出: tensor([1., 2., 5., 6.])

torch.Size([1, 4, 9])
tensor([1., 2., 5., 6.])


In [17]:
import torch
import torch.nn.functional as F

# 输入图像（6x6，对角线边缘）
X = torch.tensor([[
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 0, 0, 0],
    [0, 0, 0, 1, 1, 1],
    [0, 0, 0, 1, 1, 1],
    [0, 0, 0, 1, 1, 1]
]], dtype=torch.float32).unsqueeze(0)  # 形状 [1,1,6,6]

# 二阶导数核（拉普拉斯）
laplacian = torch.tensor([[
    [0,  1, 0],
    [1, -4, 1],
    [0,  1, 0]
]], dtype=torch.float32).unsqueeze(0)  # 形状 [1,1,3,3]

# 积分核（均值滤波）
integral = torch.ones(1, 1, 3, 3) / 9.0

# 计算卷积
output_laplacian = F.conv2d(X, laplacian, padding=1)  # 二阶导数
output_integral = F.conv2d(X, integral, padding=1)    # 积分

print("二阶导数结果:\n", output_laplacian.squeeze())
print("\n积分结果:\n", output_integral.squeeze())

二阶导数结果:
 tensor([[-2., -1., -2.,  1.,  0.,  0.],
        [-1.,  0., -1.,  1.,  0.,  0.],
        [-2., -1., -2.,  2.,  1.,  1.],
        [ 1.,  1.,  2., -2., -1., -2.],
        [ 0.,  0.,  1., -1.,  0., -1.],
        [ 0.,  0.,  1., -2., -1., -2.]])

积分结果:
 tensor([[0.4444, 0.6667, 0.4444, 0.2222, 0.0000, 0.0000],
        [0.6667, 1.0000, 0.6667, 0.3333, 0.0000, 0.0000],
        [0.4444, 0.6667, 0.5556, 0.4444, 0.3333, 0.2222],
        [0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.4444],
        [0.0000, 0.0000, 0.3333, 0.6667, 1.0000, 0.6667],
        [0.0000, 0.0000, 0.2222, 0.4444, 0.6667, 0.4444]])


[Discussions](https://discuss.d2l.ai/t/1848)
